### ISSUE TITLE
Formatting of frontend in the Mess Menu section

### ISSUE THREAD

**Issue by divc13** [Ashu3208/MessAutomationSystem#28] opened 2023-04-07 09:13 UTC
The buttons of days like "Monday", "Tuesday" are not evidently button. It was not at clear that these are clickable buttons.

Also the text "Regular:" and "Extras:" should be given different colors because it the text is not much readable due to same text colors of heading and elements.

**Comment by Ashu3208** [comment] 2023-04-09 15:06
This is not a bug related issue. Also when the mess menu page is loaded,  a centralised heading "Monday Menu" is shown.
It's evident that to view other day's menu, we have to click on the respective days.
The design of the frontend can be improved though in the next iteration of the software .
Please close the issue if satisfied

**Closed** 2023-04-09 15:13 UTC
