### ISSUE TITLE
Duplicate rebate requests.

### ISSUE THREAD

**Issue by Law1912** [Ashu3208/MessAutomationSystem#49] opened 2023-04-09 16:00 UTC
If there exists a rebate request for a date
![image](https://user-images.githubusercontent.com/106760756/230782968-7a4dce66-4ae7-429f-9f0b-59add4918323.png)
Still the user is able to make the same request again
![image](https://user-images.githubusercontent.com/106760756/230783275-c481a1bf-64a8-4fb5-8830-4aeebd44aca9.png)
which the admin is also able to accept
![image](https://user-images.githubusercontent.com/106760756/230783310-be0adb4c-9dc6-4d90-8519-cb55e07e6561.png)

**Comment by sawanhn** [comment] 2023-04-13 11:15
this issue has been resolved, now any overlap with the existing request will not be regestered .

**Comment by divc13** [comment] 2023-04-13 17:05
There are few issues left:

1. If manager accepts some request and then student removes it from his history, then student is able to apply the rebate request again.
2. Only exact same rebate requests must not be allowed. Overlapping rebate requests can be allowed.
3. If manager rejects some rebate requests, then student should be able to apply the same request again.

**Comment by Ashu3208** [comment] 2023-04-13 17:11
Allowing overlapping request does not make sense. A student is able to see his rebate request. So he should meticulously choose the dates.  Even if u consider the offline scenario, it's not like you apply for rebate multiple times. For a  continuous period of vacation, only and only one rebate request is allowed.
Kindly close the issue is satisfied.

**Closed** 2023-04-16 07:57 UTC
