### ISSUE TITLE
Student cannot book extras that are mention in the mess menu

### ISSUE THREAD

**Issue by divc13** [Ashu3208/MessAutomationSystem#20] opened 2023-04-07 06:36 UTC
Or it could be said that there is no sync between the extras mentioned separately and the weekly extras mentioned in the mess menu.

![image](https://user-images.githubusercontent.com/110289042/230555179-78882f87-3737-4a16-8d81-a00b9d539106.png)

![WhatsApp Image 2023-04-07 at 12 03 47](https://user-images.githubusercontent.com/110289042/230555216-dca869dc-4370-4808-a00e-f680f109f8da.jpg)

These extras cannot be booked.

**Comment by divc13** [comment] 2023-04-07 06:40
![image](https://user-images.githubusercontent.com/110289042/230555794-262b0469-b858-4d91-8d01-595aed8b7880.png)
 These extras are significantly different and can bee booked

**Comment by Ashu3208** [comment] 2023-04-09 18:55
@divc13 The Extras on the mess menu are just to show the menu. To be able to book the extra, the manager has to add that extra in the extras page. This is not a bug , this is how we developed the website.
Please close the issue if satisfied.

**Closed** 2023-04-10 16:23 UTC
